society/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from society_reg import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('',include('society_reg.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

society_reg/urls.py
from . import views
from django.urls import path
from django.conf.urls import url
 


urlpatterns = [
    path('',views.home,name="home"),
    path('registration/',views.register,name="reg"),
    path('society/',views.society),
    path('visitorList/', views.visitorList),
    path('userList/', views.societyList),
    path('register/', views.RegisterView.as_view(), name='auth_register'),
    path('visitordetails/<int:pk>/', views.visitordetails),
    path('login/', views.login_view,name='login'),
    path('logout/',views.logout_view,name="logout"),
    path('user/',views.userpage,name="user"),
    path('visitor_info/<int:pk>/',views.visitor_info,name="visitor_info"),
    path('update_visitor/<int:pk>/',views.updatevisitor,name="updatevisitor"),
    # path('add_flat/<int:pk>/',views.addFlat,name="addflat"),
    path('add_visitor/',views.add_visitor,name="add_visitor"),

] 

society_reg/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.contrib.auth.models import Group
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager


class CustomSocietyManager(BaseUserManager):
    def create_society(self,society_user,name,email,password,**other_fields):
        if not society_user:
            raise ValueError(_('You must provide Society User'))
        email = self.normalize_email(email)
        society = self.model(society_user=society_user,name=name,email=email,**other_fields)

        society.set_password(password)
        society.save()
        return society

    def create_superuser(self,society_user,name,email,password, **other_fields):
        other_fields.setdefault('is_staff',True)
        other_fields.setdefault('is_superuser',True)
        other_fields.setdefault('is_active',True)


        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.'
            )

        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.'
            )

        return self.create_society(society_user,name,email,password, **other_fields)
    

class Society(AbstractBaseUser,PermissionsMixin):
    society_user = models.CharField(max_length=200,unique=True)
    email = models.EmailField(_('email address'),unique=True)
    name = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    address = models.TextField(_('address'),max_length=500,blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomSocietyManager()
    USERNAME_FIELD = 'society_user'
    REQUIRED_FIELDS = ['email','name']


        
    def __str__(self):
        return self.society_user
    








class Visitor(models.Model):


    VEHICLE = (
        ('None','No vehicle'),
        ('Bike','Bike'),
        ('Car','Car')
    )




    
    vname = models.CharField(max_length =200,null=True)
    phone = models.CharField(max_length =200,null=True,blank=True, help_text='Contact phone number')
    vehicle = models.CharField(max_length =200,null=True,choices =  VEHICLE)
    in_time = models.DateTimeField(auto_now_add =True,blank=True,null=True)
    society = models.ForeignKey(Society,null=True, blank =True,on_delete=models.CASCADE)
    wing = models.CharField(max_length =200,null=True)
    flat_no = models.CharField(max_length =200,null=True)
    purpose = models.CharField(max_length =200,null=True)
    out_time = models.DateTimeField(blank=True,null=True)
    
    

   
    def __str__(self):
        return self.vname
    

society_reg/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm,UsernameField
from django import forms
#from django.contrib.auth.models import User


class CreateSocietyForm(UserCreationForm):
	class Meta:
		model = Society
		fields = ['society_user','name','email','password1','password2']
	

	

class CreateVisitorForm(ModelForm):
	class Meta:
		model = Visitor
		fields = '__all__'
		

class UpdateVisitorForm(ModelForm):
	class Meta:
		model = Visitor
		fields = '__all__'
		# exclude = ['in_time']



# class FlatForm(ModelForm):

# 	class Meta:
# 		model = Flat
# 		fields = '__all__'

# 		exclude = ['society']

society_reg/views.py
from django.shortcuts import render,redirect
from .models import *
from django.http import HttpResponse
from .forms import CreateSocietyForm,CreateVisitorForm,UpdateVisitorForm
#from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .serializers import visitorSerializer,RegisterSerializer, societySerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django import template
from rest_framework.decorators import api_view
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated,AllowAny
from django.contrib.auth import authenticate,login,logout
from .decorators import unauthenticated_user,allowed_user,admin_only
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def home(request):
	visitors = Visitor.objects.all()
	
	context = {'visitors':visitors}
	if request.user.is_staff:	
		return render(request,'society_reg/home.html',context)
	else:
		return redirect('user')



def register(request):

	form =  CreateSocietyForm()
	if request.method == 'POST':
		form =  CreateSocietyForm(request.POST)
		#print(dir(form))
		if form.is_valid():

			user = form.save()
			username = form.cleaned_data.get('username')
		
			messages.success(request,"Account was created for " + username)

			

			return redirect('home')
	context = {'register':form}
	return render(request,'society_reg/registration.html',context)


def visitor(request):
    visitors = Visitor.objects.all()

    context = {'visitors':visitors}

    return render(request,'society_reg/visitor.html',context)

@login_required(login_url='login')
@api_view(['GET', 'POST'])
def visitorList(request):

	print(request.user)
	if request.method == 'GET':
		visitors = request.user.visitor_set.all()
		serializer = visitorSerializer(visitors,many=True)
		
		return Response(serializer.data)

	elif request.method == 'POST':
		
		serializer = visitorSerializer(data=request.data)

		if serializer.is_valid():
			serializer.save()

		return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@login_required(login_url='login')
@api_view(['GET'])
def society(request):
     if request.method == 'GET':
         society = Society.objects.all()
         serializer = societySerializer(society,many=True)
		
         return Response(serializer.data)

     elif request.method == 'POST':
		
        serializer = societySerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
             
@login_required(login_url='login')             
@api_view(['GET'])
def societyList(request):

    if request.method == 'GET':
        print(dir(request.user))
        content = {
			'id': str(request.user.id),
			'user': str(request.user),
			'password': str(request.user.password),
			'auth': str(request.auth),  # None
		}
        return Response(content)



class RegisterView(generics.CreateAPIView):
    queryset = Society.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer




@api_view(['GET', 'PUT', 'DELETE'])
def visitordetails(request,pk):
		try:
			visitors =  Visitor.objects.get(id = pk)
		except Visitor.DoesNotExist:
			return Response(status=status.HTTP_404_NOT_FOUND)

		if request.method == 'GET':
			serializer =  visitorSerializer(visitors)
			return Response(serializer.data)

		elif request.method == 'PUT':
			serializer = visitorSerializer(visitors, data=request.data)
			if serializer.is_valid():
				serializer.save()
				return Response(serializer.data)
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

		elif request.method == 'DELETE':
			visitors.delete()
			return Response(status=status.HTTP_204_NO_CONTENT)
		

@unauthenticated_user
def login_view(request):
    print(dir(Society))
    if request.method == 'POST':
        society_user = request.POST.get('society_user')
        password = request.POST.get('password')
 
    
        user = authenticate(request,username=society_user,password=password)

        if user is not None:
          
            login(request, user)
            return redirect('home')
        else:
            messages.info(request,'Username OR password is incorrect')



    context = {'messages':messages}
    
    

    return render(request,'society_reg/login.html',context)


def logout_view(request):
	logout(request)

	return redirect('login')



@login_required(login_url='login')
@allowed_user(allowed_roles=['Society'])
def userpage(request):

	visitors = request.user.visitor_set.get_queryset().order_by('id')
	print(request.user.visitor_set)

	#visitors = Visitor.objects.all()


	

	total_visitors = visitors.count()

	

	page = request.GET.get('page', 1)

	paginator = Paginator(visitors, 10)
	try:
	    visitors = paginator.page(page)
	except PageNotAnInteger:
		visitors = paginator.page(1)
	except EmptyPage:
		visitors = paginator.page(paginator.num_pages)


	context = {'visitors':visitors,'total_visitors':total_visitors}
	return render(request,'society_reg/society.html',context)


def visitor_info(request,pk):

	#cust = request.user.customer
	#form = CustomerForm(instance=cust)


	visitors = Visitor.objects.get(id = pk)
	#orders = customer.order_set.all()
	#total_orders = orders.count()

	#print(customer.profile_pic)


	context = {'visitors':visitors }
	return render(request,'society_reg/visitor_info.html',context)


def updatevisitor(request,pk):
		#visitors = Visitor.objects.get(id=pk)
		society = request.user.visitor_set.get(id=pk)
		print(request.user)
		form = UpdateVisitorForm(instance=society)
		if request.method == "POST":
		#print('Printing Post',request.POST)
			
			form = UpdateVisitorForm(request.POST)
			if form.is_valid():
				print(society.vname)
				form.save()
				return redirect('home')
		context = {'form':form,'visitors':society}	
		return render(request,'society_reg/update_visitor.html',context)



# @login_required(login_url='login')
# @allowed_user(allowed_roles=['Society'])
# def addFlat(request,pk):
# 	society = Society.objects.get(id=pk)
# 	form = FlatForm(instance=society)

	
# 	if request.method == 'POST':
# 		form = FlatForm(request.POST,instance=society)
# 		if form.is_valid():
# 			form.save()
# 			return redirect('home')

# 	context = {'form':form }

# 	return render(request,'society_reg/add_flat.html',context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['Society'])

def add_visitor(request):
    #print(request.user)
    #society = Society.objects.filter(society_user=request.user)
    #print(society)
    form = CreateVisitorForm()
    
    
    if request.method == 'POST':
        form = CreateVisitorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user')

    context = {'form':form }

    return render(request,'society_reg/add_visitor.html',context)

society_reg/templates/society_reg/add_flat.html
{%  extends 'society_reg/main.html' %}
{% load static %}
{% block content %}


<div class="d-flex justify-content-center">
	<div class="row">
		<div class="col-md">
			<div class="card card-body">


				<form action="" method="POST">
					{% csrf_token %}
                    {{form.society.label}}
                    {{form.society}}
                    <hr>
                    {{form.wing.label}}
                    {{form.wing}}
                    <hr>
                    {{form.flat_no.label}}
                    {{form.flat_no}}
                    <hr>
				<input type="submit" name="Submit">
				</form>
				

					<hr>
			</div>
		</div>
	</div>
</div>
{% endblock %}

society_reg/templates/society_reg/add_visitor.html
{%  extends 'society_reg/main.html' %}
{% load static %}
{% block content %}


<div class="d-flex justify-content-center">
	<div class="row">
		<div class="col-md">
			<div class="card card-body">


			
                
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    



                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Name</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <input class="form-control form-control-solid form-control-lg" name="vname" type="text"  value="">
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                
                                    <hr>
                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Phone</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <input class="form-control form-control-solid form-control-lg" name="phone" type="text"  value="">
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                                  
                                    <hr>
                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Vehicle</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <!-- <input class="form-control form-control-solid form-control-lg" name="vehicle" type="select"> -->
                                            {{ form.vehicle}}
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                                    
                                    
                                    <hr>
                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Society</label>
                                        <div class="col-lg-9 col-xl-9">
                                          {{form.society}}
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                                    
                                    
                                    <hr>

                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Wing</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <!-- <input class="form-control form-control-solid form-control-lg" name="wing" type="select" value='{{form.wing.value}}'>
                                            <option value = '{{form.wing}}'>{{ form.wing}}<option> -->
                                                {{ form.wing}}
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                                    
                                    <hr>
                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Flat No</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <!-- <input class="form-control form-control-solid form-control-lg" name="flat_no" type="select" > -->
                                            {{form.flat_no}}
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                                  
                                    <hr>

                                    <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Purpose</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <input class="form-control form-control-solid form-control-lg" name="purpose" type="text" >
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                            
                                    <!-- <div class="form-group row fv-plugins-icon-container">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Out Time</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <input class="form-control form-control-solid form-control-lg" name="out_time" type="text" >
                                        <div class="fv-plugins-message-container"></div></div>
                                    </div>
                          -->
                              
                                <input type="submit" name="Submit">
                                </form>
                                
				

			</div>
		</div>
	</div>
</div>
{% endblock %}

society_reg/templates/society_reg/home.html
{% extends 'society_reg/main.html' %}


{% block content%}
{% load static %}

{% if request.user.is_staff %}
Admin
{% else %}

Society
{% endif %}


{% endblock %}

society_reg/templates/society_reg/login.html
<!DOCTYPE html>
<!--
Template Name: Metronic - Bootstrap 4 HTML, React, Angular 9 & VueJS Admin Dashboard Theme
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: https://1.envato.market/EA4JP
Renew Support: https://1.envato.market/EA4JP
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<html lang="en">
	<!--begin::Head-->
	<head>
		{% load static %}
		<!--base href="../../../../"-->
		<meta charset="utf-8" />
		
		<title>Login</title>
		<meta name="description" content="Login page example" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Page Custom Styles(used by this page)-->
		
		<link href="{% static 'assets/css/pages/login/classic/login-3.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Page Custom Styles-->
		<!--begin::Global Theme Styles(used by all pages)-->
		<link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Global Theme Styles-->
		<!--begin::Layout Themes(used by all pages)-->
		<link href="{% static 'assets/css/themes/layout/header/base/light.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/themes/layout/header/menu/light.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/themes/layout/brand/dark.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/themes/layout/aside/dark.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Layout Themes-->
		<link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico' %}" />
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading">
		<!--begin::Main-->
		<div class="d-flex flex-column flex-root">
			<!--begin::Login-->
			<div class="login login-3 login-signin-on d-flex flex-row-fluid" id="kt_login">
				<div class="d-flex flex-center bgi-size-cover bgi-no-repeat flex-row-fluid" style="background-image:url(/static/assets/media/bg/bg-1.jpg);">
					<div class="login-form text-center text-white p-7 position-relative overflow-hidden">
						<!--begin::Login Header-->
						<div class="d-flex flex-center mb-15">
							<a href="#">
								<img src="{% static 'assets/media/logos/logo-letter-9.png' %}" class="max-h-100px" alt="" />
							</a>
						</div>
						<!--end::Login Header-->
						<!--begin::Login Sign in form-->
						<div class="login-signin">
							<div class="mb-20">
								<h3>Sign In To Admin</h3>
								<p class="opacity-60 font-weight-bold">Enter your details to login to your account:</p>
							</div>
							<form class="form" id="kt_login_signin_form" method="POST">
								{% csrf_token %}
								<div class="form-group">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8 mb-5" type="text" placeholder="Username" name="society_user" autocomplete="on" />
								</div>
								<div class="form-group">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8 mb-5" type="password" placeholder="Password" name="password" />
								</div>
								
								<div class="form-group d-flex flex-wrap justify-content-between align-items-center px-8">
									<label class="checkbox checkbox-outline checkbox-white text-white m-0">
									<input type="checkbox" name="remember" />Remember me
									<span></span></label>
									<a href="javascript:;" id="kt_login_forgot" class="text-white font-weight-bold">Forget Password ?</a>
								</div>
								<div class="form-group text-center mt-10">
									<button id="kt_login_signin_submit" class="btn btn-pill btn-outline-white font-weight-bold opacity-90 px-15 py-3">Sign In</button>
								</div>
							
							</form>
							<div class="mt-10">
								<span class="opacity-70 mr-4">Don't have an account yet?</span>
								<a href="" id="" class="text-white font-weight-bold">Sign Up</a>
							</div>
						</div>
						<!--end::Login Sign in form-->
						<!--begin::Login Sign up form-->
						<!-- <div class="login-signup">
							<div class="mb-20">
								<h3>Sign Up</h3>
								<p class="opacity-60">Enter your details to create your account</p>
							</div>
							<form class="form text-center" id="kt_login_signup_form" method='POST'>
								{% csrf_token %}
								<div class="form-group">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8" type="text" placeholder="Fullname" name="{{signup.username}}" />
									
								</div>
								<div class="form-group">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8" type="text" placeholder="Email" name="{{signup.email}}" autocomplete="off" />
									
								</div>
								<div class="form-group">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8" type="password" placeholder="Password" name="{{signup.password1}}" />
									
								</div>
								<div class="form-group">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8" type="password" placeholder="Confirm Password" name="{{signup.password2}}" />
									
								</div>
								<div class="form-group text-left px-8">
									<label class="checkbox checkbox-outline checkbox-white text-white m-0">
									<input type="checkbox" name="agree" />I Agree the
									<a href="#" class="text-white font-weight-bold">terms and conditions</a>.
									<span></span></label>
									<div class="form-text text-muted text-center"></div>
								</div>
								<div class="form-group">
									<button id="kt_login_signup_submit" class="btn btn-pill btn-outline-white font-weight-bold opacity-90 px-15 py-3 m-2">Sign Up</button>
									<button id="kt_login_signup_cancel" class="btn btn-pill btn-outline-white font-weight-bold opacity-70 px-15 py-3 m-2">Cancel</button>
								</div>
							</form>
						</div> -->
						<!--end::Login Sign up form-->
						<!--begin::Login forgot password form-->
						<div class="login-forgot">
							<div class="mb-20">
								<h3>Forgotten Password ?</h3>
								<p class="opacity-60">Enter your email to reset your password</p>
							</div>
							<form class="form" id="kt_login_forgot_form">
								<div class="form-group mb-10">
									<input class="form-control h-auto text-white placeholder-white opacity-70 bg-dark-o-70 rounded-pill border-0 py-4 px-8" type="text" placeholder="Email" name="email" autocomplete="off" />
								</div>
								<div class="form-group">
									<button id="kt_login_forgot_submit" class="btn btn-pill btn-outline-white font-weight-bold opacity-90 px-15 py-3 m-2">Request</button>
									<button id="kt_login_forgot_cancel" class="btn btn-pill btn-outline-white font-weight-bold opacity-70 px-15 py-3 m-2">Cancel</button>
								</div>
							</form>
						</div>
						<!--end::Login forgot password form-->
					</div>
				</div>
			</div>
			<!--end::Login-->
		</div>
		<!--end::Main-->
		<script>var HOST_URL = "https://keenthemes.com/metronic/tools/preview";</script>
		<!--begin::Global Config(global config for global JS scripts)-->
		<script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#3699FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#F3F6F9", "dark": "#212121" }, "light": { "white": "#ffffff", "primary": "#E1F0FF", "secondary": "#ECF0F3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#212121", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#ECF0F3", "gray-300": "#E5EAEE", "gray-400": "#D6D6E0", "gray-500": "#B5B5C3", "gray-600": "#80808F", "gray-700": "#464E5F", "gray-800": "#1B283F", "gray-900": "#212121" } }, "font-family": "Poppins" };</script>
		<!--end::Global Config-->
		<!--begin::Global Theme Bundle(used by all pages)-->
		<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
		<script src="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
		<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
		<!--end::Global Theme Bundle-->
		<!--begin::Page Scripts(used by this page)-->
		<script src="{% static 'assets/js/pages/custom/login/login-general.js' %}"></script>
		<!--end::Page Scripts-->
	</body>
	<!--end::Body-->
</html>

society_reg/templates/society_reg/registration.html
{{register}}

society_reg/templates/society_reg/update_visitor.html
{%  extends 'society_reg/main.html' %}
{% load static %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>


$(
    function(){
     
        $('#time').click(function(){
									var time = moment().format('YYYY-MM-DD HH:mm:ss');
                  $('#id_out_time').val(time);  
        });
        
    }
);


</script>
<div class="d-flex justify-content-center">
	<div class="row">
		<div class="col-md">
			<div class="card card-body">


				<form action="" method="POST">
					{% csrf_token %}
					
					<b>Name</b> : {{form.vname}}
					<hr>
					<b>{{form.phone.label}}</b> : {{form.phone}}
					<hr>

					<b>{{form.vehicle.label}}</b> : {{form.vehicle}}
					<hr>
					<b>{{form.society.label}}</b> : {{form.society}}
					<hr>
					<b>{{form.wing.label}}</b> : {{ form.wing}}
					<hr>
                    <b>{{form.flat_no.label}}</b> : {{form.flat_no}}
					<hr>

                    <b>{{form.out_time.label}}</b>
                   
				
					
					<input type="text" name='{{form.out_time.name}}' value='{{form.out_time.value}}'  id="id_out_time" >
					<input type="button" value="Check Out"  id="time">
					<hr>

				<input type="submit" name="Submit">
				</form>
				

				<!-- <input type='text'  id='{{form.name}}' name = 'out_time' value="">
					<button id='{{visitors.id}}' onClick="show(this.id)">Check Out</button> -->
					<hr>
			</div>
		</div>
	</div>
</div>
{% endblock %}


<!-- <b>{{form.out_time.label}}</b> : {{form.out_time}} -->